# Generated by Django 4.0.3 on 2022-03-09 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_user_bio_user_course_user_student_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_and_section',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
