# Generated by Django 4.0.3 on 2022-03-10 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='course',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_no',
            field=models.IntegerField(default=100000),
        ),
        migrations.AlterField(
            model_name='user',
            name='year_and_section',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
