# Generated by Django 4.0.3 on 2022-03-13 05:21

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_user_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=account.models.get_profile_image_filepath),
        ),
    ]
